version: "3.8"
services:
  web:
    build:
      context: .
    ports:
      - "80:5000"
    volumes:
      - ./:/app
    deploy:
      restart_policy:
        condition: any

  updater:
    build:
      context: .
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./:/app
    deploy:
      restart_policy:
        condition: any